sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build AlexRosengarten_Resume.tex
deploy:
  provider: releases
  user: alxrsngrtn
  password:
    secure: sRB8oQw987tR+FBiDvWqca/McROrd04isRAq5cO3y3UsvlkC8oUM9AmIW3EbQ/TySSHhENYcPt6FatoUWn7yk/keCO+BecvBKdASWhZoKt6RrnxcL7uQNxYvFYIFEX96BeODMttwiNqCYNR7jovUX8TORxdpNreshk9N1uMXCAYJWbYEWKf8a1haVoRR/7QXXCNoXggz8IoeZQeqvqHrN4B2mms2/aoHkj+uH+LoPvNV0AD6w+5PgRxAA1nJuMUJ4TDbagNJqsYzcJz9uJB0DFl2UwoYWLAwv/y6KTh3mRIhXz0I/6z/Qb75lnT8kXEZVg4wNHJ9nLMIwY/pVCa4A7mNpW7shUCknVwP0rr2O+of1jrYgN1lWzyvfeSv1eAgu/fpGTsoDQHiMdK40GWMpp5+TQnYeBs4uH0rm4eHYKgpxeYGB9tDTjDWMuWF0BhQcxenV0PKePXu7tVDLAAjd4d+NFVoB2u9wUHs5sJLJ9XHdY0DyQZ0UflubxVp8vRW3UnGPiChhQTU+fu8+hhKMPNsFKcuzTKSosIxNSY4JzHYejmyLDlZA2k5G9DEPvgxKh8Eng/z0iYEihjTPAZ4kGKS97Arzg1ZPFj/HToWr9wrxDJTK+1emFrezLb0VN6pZo0xynEkS+j4zWXb+QqZzR7VECyeGY2nojS3YvVCPP0=
  file: _build/AlexRosengarten_Resume.pdf
  on:
    tags: true
